### ISSUE TITLE
tag not working

### ISSUE THREAD

**Issue by swissbuechi** [mattdavis0351/actions#23]
![image](https://user-images.githubusercontent.com/24353767/95221769-16c19000-07f8-11eb-802e-dc4fa6aec631.png)

```
name: Docker Container

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  jar:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
         java-version: 1.8
         server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
         settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn package -DskipTests

      - name: Upload .jar for Docker Image
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: ./target/PrimeDbApi.jar
  image:
    # Ensure test job passes before pushing image.
    needs: jar

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download .jar for Docker Image
        uses: actions/download-artifact@v2
        with:
          name: target
          path: ./target
      - name: Build, Tag, Push
        uses: mattdavis0351/actions/docker-gpr@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: primedbapi
          tag: latest
```
